// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gestao_hq_backend.Infrastructure.Data;

#nullable disable

namespace gestao_hq_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gestao_hq_backend.Domain.Entities.Edicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HqId")
                        .HasColumnType("integer");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("HqId");

                    b.ToTable("Edicoes");
                });

            modelBuilder.Entity("gestao_hq_backend.Domain.Entities.Editora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeEditora")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Editoras");
                });

            modelBuilder.Entity("gestao_hq_backend.Domain.Entities.HQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeHq")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeOriginalHq")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Publicacao")
                        .HasColumnType("integer");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TotalEdicoes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("HQs");
                });

            modelBuilder.Entity("gestao_hq_backend.Domain.Entities.HqEditora", b =>
                {
                    b.Property<int>("HqId")
                        .HasColumnType("integer");

                    b.Property<int>("EditoraId")
                        .HasColumnType("integer");

                    b.HasKey("HqId", "EditoraId");

                    b.HasIndex("EditoraId");

                    b.ToTable("HqEditoras");
                });

            modelBuilder.Entity("gestao_hq_backend.Domain.Entities.HqPersonagem", b =>
                {
                    b.Property<int>("HqId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("integer");

                    b.HasKey("HqId", "PersonagemId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("HqPersonagens");
                });

            modelBuilder.Entity("gestao_hq_backend.Domain.Entities.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TipoPersonagem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("gestao_hq_backend.Domain.Entities.Edicao", b =>
                {
                    b.HasOne("gestao_hq_backend.Domain.Entities.HQ", "Hq")
                        .WithMany("Edicoes")
                        .HasForeignKey("HqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hq");
                });

            modelBuilder.Entity("gestao_hq_backend.Domain.Entities.HqEditora", b =>
                {
                    b.HasOne("gestao_hq_backend.Domain.Entities.Editora", "Editora")
                        .WithMany("HqEditoras")
                        .HasForeignKey("EditoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestao_hq_backend.Domain.Entities.HQ", "Hq")
                        .WithMany("HqEditoras")
                        .HasForeignKey("HqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editora");

                    b.Navigation("Hq");
                });

            modelBuilder.Entity("gestao_hq_backend.Domain.Entities.HqPersonagem", b =>
                {
                    b.HasOne("gestao_hq_backend.Domain.Entities.HQ", "Hq")
                        .WithMany("HqPersonagens")
                        .HasForeignKey("HqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestao_hq_backend.Domain.Entities.Personagem", "Personagem")
                        .WithMany("HqPersonagens")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hq");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("gestao_hq_backend.Domain.Entities.Editora", b =>
                {
                    b.Navigation("HqEditoras");
                });

            modelBuilder.Entity("gestao_hq_backend.Domain.Entities.HQ", b =>
                {
                    b.Navigation("Edicoes");

                    b.Navigation("HqEditoras");

                    b.Navigation("HqPersonagens");
                });

            modelBuilder.Entity("gestao_hq_backend.Domain.Entities.Personagem", b =>
                {
                    b.Navigation("HqPersonagens");
                });
#pragma warning restore 612, 618
        }
    }
}
